name: crud_golang
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Base de datos local
  sqflite: ^2.2.8+4
  path: ^1.8.3

  # HTTP
  http: ^1.1.0
  chopper: ^7.0.5

  # Conectividad (actualizada)
  connectivity_plus: ^7.0.0

  # Serialización JSON
  json_annotation: ^4.9.0
  # web
  sembast: ^3.7.1
  sembast_web: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generación de código
  build_runner: ^2.4.13
  chopper_generator: ^7.0.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
